services:
  study:
    image: byjg/nginx-extras
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./data:/usr/share/nginx/html/
      - ./Nginx-Fancyindex-Theme-light:/usr/share/nginx/html/Nginx-Fancyindex-Theme-light
      - ./Nginx-Fancyindex-Theme-dark:/usr/share/nginx/html/Nginx-Fancyindex-Theme-dark
    restart: always
